### ISSUE TITLE
Suggestion: Add a "Mob damage" flag

### ISSUE THREAD

**Issue by AlexPads** [ProxmaDev/AreaProtection#3]
Could a mob damage flag be added to the Plugin so that people don't walk creepers to the area and explode them?

**Comment by ProxmaDev** [comment]
I added an explosion flag in AreaProtection 2.0.0. AreaProtection 2.0.0 will be released today or tommorow.

With this flag you can prevent creepers & tnt from damaging your protected areas.

**Comment by ProxmaDev** [comment]
added.
